---
AWSTemplateFormatVersion: '2010-09-09'


Metadata:

  AWS::CloudFormation::Interface:
    ParameterLabels:
      DomainName: {default: CloudFront Distribution FQDN}
      CertificateArn: {default: CloudFront Distribution ACM Certificate}
      DefaultTTL: {default: Default time to cache objects in seconds}
      MaxTTL: {default: Maximum time to cache objects in seconds}
    ParameterGroups:
      - Label: {default: Website Settings}
        Parameters:
          - DomainName
      - Label: {default: CloudFront Settings}
        Parameters:
          - CertificateArn
          - DefaultTTL
          - MaxTTL


Parameters:

  DomainName:
    Type: String
    Description: FQDN
    Default: ''

  CertificateArn:
    Type: String
    Description: Arn
    Default: arn:aws:acm:us-east-1:333680067100:certificate/9f20a979-8996-43e7-9c92-b9a0b4999345

  DefaultTTL:
    Type: Number
    Description: Default Time in Seconds to cache objects
    Default: 86400
    MinValue: 0
    MaxValue: 31536000

  MaxTTL:
    Type: Number
    Description: Maximum Time in Seconds to cache objects
    Default: 31536000
    MinValue: 3600
    MaxValue: 31536000


Outputs:

  BucketWebsite:
    Value: !Ref WebBucket

  CNAMEWebsite:
    Value: !GetAtt WebServer.DomainName

  CloudFrontWebsite:
    Value: !Sub https://console.aws.amazon.com/cloudfront/home?region=${AWS::Region}#distribution-settings:${WebServer}


Resources:

  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      VersioningConfiguration: { Status: Enabled }
      LifecycleConfiguration:
        Rules:
          - Id: SevenYearHoldDeleted
            Status: Enabled
            NoncurrentVersionExpirationInDays: 2555

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub ${WebBucket.Arn}/*
            Principal: '*'

  WebServer:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref FQDN
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 86400
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: !Sub ${WebBucket}.s3-website-${AWS::Region}.amazonaws.com
          Compress: true
          ForwardedValues:
            QueryString: false
          DefaultTTL: !Ref DefaultTTL
          MaxTTL: !Ref MaxTTL
          AllowedMethods: [HEAD, GET, OPTIONS]
        Origins:
          - Id: !Sub ${WebBucket}.s3-website-${AWS::Region}.amazonaws.com
            CustomOriginConfig: {OriginProtocolPolicy: http-only}
            DomainName: !Sub ${WebBucket}.s3-website-${AWS::Region}.amazonaws.com
...
